/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileSettingsImport } from './routes/profile/settings'
import { Route as ContactsContactIdIndexImport } from './routes/contacts.$contactId.index'
import { Route as ContactsContactIdEditImport } from './routes/contacts.$contactId.edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRoute,
} as any)

const ContactsContactIdIndexRoute = ContactsContactIdIndexImport.update({
  id: '/contacts/$contactId/',
  path: '/contacts/$contactId/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsContactIdEditRoute = ContactsContactIdEditImport.update({
  id: '/contacts/$contactId/edit',
  path: '/contacts/$contactId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId/edit': {
      id: '/contacts/$contactId/edit'
      path: '/contacts/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof ContactsContactIdEditImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactId/': {
      id: '/contacts/$contactId/'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/contacts/$contactId/edit': typeof ContactsContactIdEditRoute
  '/contacts/$contactId': typeof ContactsContactIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/contacts/$contactId/edit': typeof ContactsContactIdEditRoute
  '/contacts/$contactId': typeof ContactsContactIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/contacts/$contactId/edit': typeof ContactsContactIdEditRoute
  '/contacts/$contactId/': typeof ContactsContactIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile/settings'
    | '/contacts/$contactId/edit'
    | '/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile/settings'
    | '/contacts/$contactId/edit'
    | '/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile/settings'
    | '/contacts/$contactId/edit'
    | '/contacts/$contactId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ContactsContactIdEditRoute: typeof ContactsContactIdEditRoute
  ContactsContactIdIndexRoute: typeof ContactsContactIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ContactsContactIdEditRoute: ContactsContactIdEditRoute,
  ContactsContactIdIndexRoute: ContactsContactIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/profile/settings",
        "/contacts/$contactId/edit",
        "/contacts/$contactId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/profile/settings": {
      "filePath": "profile/settings.tsx"
    },
    "/contacts/$contactId/edit": {
      "filePath": "contacts.$contactId.edit.tsx"
    },
    "/contacts/$contactId/": {
      "filePath": "contacts.$contactId.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
